# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
variables:
  # Container registry service connection established during pipeline creation
  imageRepository: 'rjammalamadakapipeline'
  containerRegistry: 'testacrajsc.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/app/Dockerfile'
  tag: '$(Build.BuildId)'
steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: acrajscseeds
- task: AzureCLI@1
  inputs:
    azureSubscription: AJSC
    scriptLocation: inlineScript
    inlineScript: |
      docker login -u ajscacr -p y72Xilz2LfFYx6ei90aIdrjVwkF/U51b testacrajsc.azurecr.io
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection1)
    tags: |
      $(tag)


